endpoints:
  - path: /okta
    method: GET
    handler: handleHello
    oidc:
      issuer: https://accounts.google.com
      client_id: YOUR_CLIENT_ID
      client_secret: YOUR_CLIENT_SECRET
  - path: /someother
    method: GET
    handler: handleHello
    oidc:
      issuer: https://accounts.google.com
      client_id: YOUR_CLIENT_ID
      client_secret: YOUR_CLIENT_SECRET
